### ISSUE TITLE
Jansson Error when Build in Xcode 5

### ISSUE THREAD

**Issue by namkazt** [alfonsocejudo/EasyNDK-for-cocos2dx3#1]
i get this error.

Undefined symbols for architecture i386:
  "_json_array_get", referenced from:
      GameScene::onTouchBegan(cocos2d::Touch_, cocos2d::Event_) in GameScene.o
  "_json_array_size", referenced from:
      GameScene::onTouchBegan(cocos2d::Touch_, cocos2d::Event_) in GameScene.o
  "_json_integer_value", referenced from:
      GameScene::onTouchBegan(cocos2d::Touch_, cocos2d::Event_) in GameScene.o
  "_json_loads", referenced from:
      GameScene::onTouchBegan(cocos2d::Touch_, cocos2d::Event_) in GameScene.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by namkazt** [comment]
i solved this problems.

**Comment by mouse4d** [comment]
Could you please tell what was the problem?
thx!
